# Generated by Django 2.2 on 2019-04-10 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A short action statement describing what is to be accomplished",
                        max_length=255,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        help_text="A due date, if applicable",
                        null=True,
                        verbose_name="date due",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("megadoit", "High"),
                            ("asap", "Normal"),
                            ("meh", "Low"),
                        ],
                        default="asap",
                        help_text="A priority to complete the task",
                        max_length=255,
                    ),
                ),
                (
                    "point_value",
                    models.IntegerField(
                        default=0,
                        help_text="How many points completing the task is worth",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        help_text="A task may have children",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.Task",
                    ),
                ),
            ],
            options={"ordering": ("due_date", "priority", "point_value")},
        )
    ]
