# Generated by Django 2.2 on 2019-04-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="complete",
            field=models.BooleanField(
                default=False, help_text="Completion status of the task"
            ),
        )
    ]
